### ISSUE TITLE
Support markdown highlights

### ISSUE THREAD

**Issue by TristanH** [TedisAgolli/readwise-random-quote#1]
Often highlight text will contain markdown rather than just plaintext!

<img width="830" alt="CleanShot 2021-06-02 at 11 01 20@2x" src="https://user-images.githubusercontent.com/1284332/120530037-0d9aba00-c3ab-11eb-86bc-d6de14502da1.png">

Would be really awesome if the extension rendered markdown using something like https://github.com/evilstreak/markdown-js

**Comment by TedisAgolli** [comment]
I had not thought of this at all! I'll take a look but seems easy enough. 

PS: The actual repo for the new-tab extension is this https://github.com/TedisAgolli/readwise-new-tab
Just made it public. This is a test repo I made because I wanted to have a simple route to get a random quote for other ideas.

**Comment by TedisAgolli** [comment]
Resolved https://github.com/TedisAgolli/readwise-new-tab/issues/3
